name: Deploy Recorder Function

on:
  workflow_dispatch:
  push:
    paths:
      - 'RecordMedication/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install dependencies
      run: |
        cd RecordMedication
        npm install --production

    - name: Package function
      run: |
        cd RecordMedication
        zip -r function.zip . -x "*.git*" "*.github*"

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name record_medication --zip-file fileb://RecordMedication/function.zip
