name: Deploy Recorder Function

on:
  workflow_dispatch:
  push:
    paths:
      - 'RecordMedication/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy common folder
      run: |
        cp -r src/utils.js RecordMedication/utils.js

    - name: Install dependencies
      run: |
        cd RecordMedication
        npm install

    - name: Deploy to Lambda
      run: |
        cd RecordMedication
        zip -r function.zip .
        aws lambda update-function-code --function-name record-medication --zip-file fileb://function.zip

    - name: Clean up
      run: |
        rm -rf RecordMedication/utils.js
